services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOSTNAME=redis
      - REDIS_PASSWORD=mysecretpassword
      - REDIS_PORT=6379
  redis:
    image: "redis"
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=mysecretpassword